[build]
target-dir = "/home/marxin/.cargo/target"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]
runner = "qemu-aarch64 -L /usr/aarch64-linux-gnu/"

[target.riscv64gc-unknown-linux-gnu]
linker = "riscv64-linux-gnu-gcc"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]
runner = "qemu-riscv64 -L /usr/riscv64-linux-gnu/"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=--ld-path=wild"]

[target.wasm32-wasip1]
runner = "wasmer run --disable-cache --"
